services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "MyStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # api:
  #   build:
  #     context: ./ # Mudando o contexto para a raiz
  #     dockerfile: ./src/GerenciadorDeTarefas.API/Dockerfile # Caminho do Dockerfile relativo ao contexto
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - sqlserver
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GerenciadorDeTarefasDB;User Id=sa;Password=MyStrong@Pass123;TrustServerCertificate=True

  # frontend:
  #   build:
  #     context: ./src/gerenciadortarefas.web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - api

volumes:
  sqlserver_data: